services:
  nginx:
    volumes:
      - ./nginx/templates/finassist-init.conf.template:/etc/nginx/templates/default.conf.template:ro
      - letsencrypt:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot:ro
